package com.ewe.dingtalk_approval;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Objects;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

/**
 * 审批意见与审批决策服务。
 *
 * <p>审批人在本系统提交的“同意 / 拒绝 / 补充意见”都会：</p>
 * <ol>
 *   <li>先通过钉钉接口实时写回审批流程，保证钉钉端与本地端看到的是同一份数据；</li>
 *   <li>再在本地 {@code approval_decision} 表留痕，形成可追溯的审批时间线；</li>
 *   <li>最后重新同步一次实例状态并触发通知。</li>
 * </ol>
 *
 * <p>权限上，能否操作某张审批单完全由钉钉决定：只有钉钉把待办任务派给了当前用户，
 * 才能在实例详情的 tasks 中找到属于他的 RUNNING 任务。</p>
 */
@Service
public class ApprovalDecisionService {

    private static final Logger log = LoggerFactory.getLogger(ApprovalDecisionService.class);

    /** 审批人可执行的动作。 */
    public enum Action {
        AGREE("同意"),
        REFUSE("拒绝"),
        COMMENT("补充意见");

        private final String label;

        Action(String label) {
            this.label = label;
        }

        /** 中文描述，用于通知文案与界面展示。 */
        public String label() {
            return label;
        }

        /** 解析前端传入的动作字符串，无法识别时抛出 400。 */
        public static Action parse(String value) {
            if (value == null || value.isBlank()) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "缺少审批动作（agree / refuse）。");
            }
            return switch (value.trim().toLowerCase(java.util.Locale.ROOT)) {
                case "agree", "approve" -> AGREE;
                case "refuse", "reject" -> REFUSE;
                case "comment" -> COMMENT;
                default -> throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                        "不支持的审批动作：" + value + "，仅支持 agree / refuse / comment。");
            };
        }
    }

    /** 决策来源，区分人工操作与系统自动生成，便于审计。 */
    public static final String SOURCE_WEB = "WEB";
    public static final String SOURCE_SYSTEM = "SYSTEM";

    private final DingTalkApprovalService dingTalk;
    private final ApprovalRecordService records;
    private final ApprovalNotificationService notifications;
    private final JdbcClient jdbc;

    public ApprovalDecisionService(DingTalkApprovalService dingTalk, ApprovalRecordService records,
            ApprovalNotificationService notifications, JdbcClient jdbc) {
        this.dingTalk = dingTalk;
        this.records = records;
        this.notifications = notifications;
        this.jdbc = jdbc;
    }

    /**
     * 提交审批决策（同意 / 拒绝），并同步状态、推送通知。
     *
     * @param instanceId 审批实例 ID
     * @param userId     当前登录用户钉钉 userId
     * @param nick       当前登录用户昵称
     * @param action     审批动作，仅支持 AGREE / REFUSE
     * @param remark     审批意见，留空时由系统自动生成
     * @return 写回钉钉后的最新本地记录与本次决策留痕
     */
    public DecisionResult decide(String instanceId, String userId, String nick, Action action, String remark) {
        if (action == Action.COMMENT) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "提交审批决策时不能使用 comment 动作。");
        }

        DingTalkApprovalService.ApprovalDetail detail = dingTalk.getApprovalDetail(instanceId);
        DingTalkApprovalService.ApprovalTask task = detail.pendingTaskOf(userId);
        if (task == null) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "你在该审批单中没有待处理任务，可能已被处理或不是当前审批人。");
        }

        // 需求中的“自动生成反馈”：审批意见留空时由系统按动作生成结构化意见，
        // 明确标注为系统生成，避免与审批人的真实理由混淆。
        String finalRemark = (remark == null || remark.isBlank())
                ? autoGeneratedRemark(action, nick, userId)
                : remark.trim();

        dingTalk.decideApprovalTask(instanceId, task.taskId(), action == Action.AGREE, finalRemark);
        Decision decision = insert(instanceId, userId, nick, action, finalRemark, SOURCE_WEB);

        ApprovalRecordService.ApprovalRecord record = refreshQuietly(instanceId, userId);
        // 决策通知与状态变更通知内容重复，这里先抢占状态通知权，只发一条“审批动态”。
        records.claimNotification(instanceId, record.status());
        notifications.notifyDecision(record, userId, nick, action.label(), finalRemark);
        return new DecisionResult(decision, record);
    }

    /**
     * 追加一条审批意见（不改变审批结果）。
     *
     * <p>允许发起人与审批参与人提交，用于补充材料说明或追问。</p>
     */
    public Decision comment(String instanceId, String userId, String nick, String content) {
        if (content == null || content.isBlank()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "审批意见不能为空。");
        }
        String trimmed = content.trim();
        DingTalkApprovalService.ApprovalDetail detail = dingTalk.getApprovalDetail(instanceId);
        requireParticipant(detail, userId, instanceId);

        dingTalk.addComment(instanceId, userId, nick, trimmed);
        Decision decision = insert(instanceId, userId, nick, Action.COMMENT, trimmed, SOURCE_WEB);
        ApprovalRecordService.ApprovalRecord record = records.findOrNull(instanceId);
        if (record != null) {
            notifications.notifyDecision(record, userId, nick, Action.COMMENT.label(), trimmed);
        }
        return decision;
    }

    /** 查询某张审批单在本系统留下的审批意见时间线（按时间正序）。 */
    public List<Decision> timeline(String instanceId) {
        return jdbc.sql("""
                select id, instance_id, user_id, user_nick, action, remark, source_type, created_at
                from approval_decision where instance_id=:instanceId
                order by created_at asc, id asc
                """).param("instanceId", instanceId).query((rs, rowNum) -> new Decision(
                        rs.getLong("id"),
                        rs.getString("instance_id"),
                        rs.getString("user_id"),
                        rs.getString("user_nick"),
                        rs.getString("action"),
                        rs.getString("remark"),
                        rs.getString("source_type"),
                        rs.getObject("created_at", OffsetDateTime.class)))
                .list();
    }

    /**
     * 校验用户是否有权查看该审批单：发起人本人、任一审批任务的处理人，或钉钉返回的审批人。
     */
    public void requireVisible(DingTalkApprovalService.ApprovalDetail detail, String userId, String instanceId) {
        if (isParticipant(detail, userId)) return;
        throw new ResponseStatusException(HttpStatus.FORBIDDEN, "你不是该审批单的发起人或审批人。");
    }

    private void requireParticipant(DingTalkApprovalService.ApprovalDetail detail, String userId, String instanceId) {
        if (!isParticipant(detail, userId)) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "你不是该审批单的发起人或审批人，无法提交意见。");
        }
    }

    private boolean isParticipant(DingTalkApprovalService.ApprovalDetail detail, String userId) {
        if (userId == null) return false;
        if (userId.equals(detail.originatorUserId())) return true;
        if (detail.approverUserIds() != null && detail.approverUserIds().contains(userId)) return true;
        return detail.tasks() != null && detail.tasks().stream().filter(Objects::nonNull)
                .anyMatch(task -> userId.equals(task.userId()));
    }

    /**
     * 决策写回钉钉后重新同步本地状态。钉钉存在秒级最终一致性，
     * 同步失败不应影响已经成功的审批动作，因此这里只记录日志。
     */
    private ApprovalRecordService.ApprovalRecord refreshQuietly(String instanceId, String userId) {
        try {
            return records.syncInstance(instanceId).after();
        } catch (RuntimeException exception) {
            log.warn("审批决策已提交，但本地状态同步失败，instanceId={}", instanceId, exception);
            return records.find(instanceId);
        }
    }

    private Decision insert(String instanceId, String userId, String nick, Action action, String remark,
            String sourceType) {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        jdbc.sql("""
                insert into approval_decision(instance_id, user_id, user_nick, action, remark, source_type, created_at)
                values (:instanceId, :userId, :nick, :action, :remark, :sourceType, :createdAt)
                """).param("instanceId", instanceId).param("userId", userId).param("nick", nick)
                .param("action", action.name()).param("remark", remark).param("sourceType", sourceType)
                .param("createdAt", now).update();
        // 主键由数据库生成，这里不回读；需要主键时通过 timeline() 按时间线查询。
        return new Decision(null, instanceId, userId, nick, action.name(), remark, sourceType, now);
    }

    /**
     * 生成系统默认审批意见。明确标注来源与时间，便于在钉钉审批记录中一眼分辨。
     */
    static String autoGeneratedRemark(Action action, String nick, String userId) {
        String operator = (nick == null || nick.isBlank()) ? userId : nick;
        String conclusion = action == Action.AGREE ? "同意" : "不同意";
        return """
                %s（审批人：%s）
                该意见由 EWE 审批中心在审批人未填写理由时自动生成，具体原因请以审批人补充说明为准。"""
                .formatted(conclusion, operator);
    }

    /**
     * 一次审批决策的结果。
     *
     * @param decision 本次决策的本地留痕
     * @param record   决策后同步得到的本地审批记录
     */
    public record DecisionResult(Decision decision, ApprovalRecordService.ApprovalRecord record) {}

    /**
     * 审批意见留痕。
     *
     * @param action     AGREE / REFUSE / COMMENT
     * @param sourceType WEB 表示人工在本系统提交，SYSTEM 表示系统自动生成
     */
    public record Decision(Long id, String instanceId, String userId, String userNick, String action,
            String remark, String sourceType, OffsetDateTime createdAt) {}
}
