create table if not exists approval_record (
    instance_id varchar(128) primary key,
    originator_user_id varchar(128) not null,
    dept_id bigint,
    business_id varchar(128),
    title varchar(500),
    status varchar(32) not null,
    result varchar(32),
    created_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    synced_at timestamp with time zone not null
);

create index if not exists idx_approval_user on approval_record(originator_user_id);

create table if not exists approval_participant (
    instance_id varchar(128) not null,
    user_id varchar(128) not null,
    primary key (instance_id, user_id),
    foreign key (instance_id) references approval_record(instance_id) on delete cascade
);

create index if not exists idx_approval_participant_user on approval_participant(user_id);

create table if not exists dingtalk_event_receipt (
    event_id varchar(128) primary key,
    event_type varchar(128) not null,
    instance_id varchar(128),
    received_at timestamp with time zone not null
);

-- 审批意见与决策审计。所有写回钉钉的同意 / 拒绝 / 评论都会在此留痕，
-- 用于满足“审批流程透明可追溯”的要求，也便于排查钉钉与本地状态不一致的问题。
create table if not exists approval_decision (
    id bigint generated by default as identity primary key,
    instance_id varchar(128) not null,
    user_id varchar(128) not null,
    user_nick varchar(128),
    action varchar(32) not null,
    remark clob,
    source_type varchar(32) not null,
    created_at timestamp with time zone not null
);

create index if not exists idx_approval_decision_instance on approval_decision(instance_id, created_at);

-- 钉钉通知发送记录。发送失败不会中断主流程，但必须留痕以便补发与对账。
create table if not exists approval_notification (
    id bigint generated by default as identity primary key,
    instance_id varchar(128),
    recipient_user_id varchar(128) not null,
    event varchar(64) not null,
    channel varchar(32) not null,
    payload clob,
    status varchar(16) not null,
    error_message varchar(500),
    created_at timestamp with time zone not null
);

create index if not exists idx_approval_notification_instance on approval_notification(instance_id, created_at);

-- 记录已经针对哪个状态发过通知，避免定时同步与 Stream 事件重复推送。
alter table approval_record add column if not exists notified_status varchar(32);
