package com.ewe.dingtalk_approval;

import org.junit.jupiter.api.Test;
import org.springframework.web.server.ResponseStatusException;

import static org.junit.jupiter.api.Assertions.*;

class ApprovalDecisionServiceTests {

    @Test
    void parsesSupportedActionsIgnoringCaseAndAliases() {
        assertEquals(ApprovalDecisionService.Action.AGREE, ApprovalDecisionService.Action.parse("agree"));
        assertEquals(ApprovalDecisionService.Action.AGREE, ApprovalDecisionService.Action.parse("APPROVE"));
        assertEquals(ApprovalDecisionService.Action.REFUSE, ApprovalDecisionService.Action.parse("refuse"));
        assertEquals(ApprovalDecisionService.Action.REFUSE, ApprovalDecisionService.Action.parse("Reject"));
        assertEquals(ApprovalDecisionService.Action.COMMENT, ApprovalDecisionService.Action.parse("comment"));
    }

    @Test
    void rejectsUnknownOrMissingActions() {
        assertThrows(ResponseStatusException.class, () -> ApprovalDecisionService.Action.parse("drop"));
        assertThrows(ResponseStatusException.class, () -> ApprovalDecisionService.Action.parse(""));
        assertThrows(ResponseStatusException.class, () -> ApprovalDecisionService.Action.parse(null));
    }

    @Test
    void autoGeneratedAgreeRemarkIsMarkedAsSystemGenerated() {
        String remark = ApprovalDecisionService.autoGeneratedRemark(
                ApprovalDecisionService.Action.AGREE, "张三", "user-a");

        assertTrue(remark.startsWith("同意"));
        assertTrue(remark.contains("张三"));
        assertTrue(remark.contains("自动生成"), "必须明确标注为系统生成，避免与审批人真实理由混淆");
    }

    @Test
    void autoGeneratedRefuseRemarkFallsBackToUserIdWhenNickIsMissing() {
        String remark = ApprovalDecisionService.autoGeneratedRemark(
                ApprovalDecisionService.Action.REFUSE, "  ", "user-a");

        assertTrue(remark.startsWith("不同意"));
        assertTrue(remark.contains("user-a"));
    }
}
